version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
  spree:
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
    environment:
        DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres/${DATABASE_NAME}?pool=${RAILS_MAX_THREADS}
