version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: spree_postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  spree:
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
